<?php
/**
 * Created by PhpStorm.
 * User: hong1234
 * Date: 04.11.16
 * Time: 13:00
 */

namespace Foggyline\PaymentBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
}